name: Test

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
  
    env: 
      CAMINHO_PROJETO: ./aspnet-webapi
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 3.1.402
          
      - name: Install dependencies
        run: dotnet restore ${{ env.CAMINHO_PROJETO }}
      
      - name: Build 
        run: dotnet build ${{ env.CAMINHO_PROJETO }} --configuration Release --no-restore
